version: '3.8'

services:
  cliente-db:
    image: postgres:15
    container_name: cliente-db
    environment:
      POSTGRES_DB: cliente_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - cliente_db_data:/var/lib/postgresql/data

  cliente-service:
    build: ./
    container_name: cliente-service
    ports:
      - "8081:8081"
    depends_on:
      - cliente-db
    environment:
      SPRING_PROFILES_ACTIVE: default

volumes:
  cliente_db_data:
