spring:
  datasource:
    url: jdbc:postgresql://cliente-db:5432/cliente_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    admin:
      auto-create: false
server:
  port: 8081
  error:
    include-stacktrace: never
