spring:
  datasource:
    url: jdbc:postgresql://cliente-db:5432/cliente_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
